import { AIInsight, Patient, ProgressData, PatientVitals } from "@/types/patient";

// Extended mock data
export const mockPatients: Patient[] = [
    {
        id: 1,
        name: "Sarah Johnson",
        condition: "Lower Back Pain",
        adherenceRate: 85,
        nextSession: "2024-01-31",
        status: "Active",
        progress: "Improving",
        tokensEarned: 450,
    },
    {
        id: 2,
        name: "Michael Chen",
        condition: "Knee Rehabilitation",
        adherenceRate: 92,
        nextSession: "2024-02-01",
        status: "Active",
        progress: "Stable",
        tokensEarned: 580,
    },
    {
        id: 3,
        name: "Emily Wilson",
        condition: "Shoulder Recovery",
        adherenceRate: 78,
        nextSession: "2024-02-03",
        status: "Active",
        progress: "Improving",
        tokensEarned: 320,
    },
    {
        id: 4,
        name: "James Martinez",
        condition: "Post-Surgery Rehab",
        adherenceRate: 95,
        nextSession: "2024-02-02",
        status: "Active",
        progress: "Stable",
        tokensEarned: 640,
    },
    {
        id: 5,
        name: "Sofia Rodriguez",
        condition: "Hip Replacement",
        adherenceRate: 88,
        nextSession: "2024-02-04",
        status: "Active",
        progress: "Improving",
        tokensEarned: 490,
    },
    {
        id: 6,
        name: "David Kim",
        condition: "Ankle Sprain",
        adherenceRate: 75,
        nextSession: "2024-02-05",
        status: "Active",
        progress: "Declining",
        tokensEarned: 280,
    },
    {
        id: 7,
        name: "Lisa Thompson",
        condition: "Neck Pain",
        adherenceRate: 90,
        nextSession: "2024-02-06",
        status: "Active",
        progress: "Stable",
        tokensEarned: 520,
    },
    {
        id: 8,
        name: "Robert Taylor",
        condition: "Wrist Rehabilitation",
        adherenceRate: 82,
        nextSession: "2024-02-07",
        status: "Inactive",
        progress: "Stable",
        tokensEarned: 380,
    },
    {
        id: 9,
        name: "Maria Garcia",
        condition: "Back Surgery Recovery",
        adherenceRate: 94,
        nextSession: "2024-02-08",
        status: "Active",
        progress: "Improving",
        tokensEarned: 600,
    },
    {
        id: 10,
        name: "John Anderson",
        condition: "Rotator Cuff Injury",
        adherenceRate: 86,
        nextSession: "2024-02-09",
        status: "Active",
        progress: "Stable",
        tokensEarned: 440,
    },
    {
        id: 11,
        name: "Emma Davis",
        condition: "ACL Recovery",
        adherenceRate: 91,
        nextSession: "2024-02-10",
        status: "Active",
        progress: "Improving",
        tokensEarned: 550,
    },
    {
        id: 12,
        name: "Thomas Wright",
        condition: "Carpal Tunnel",
        adherenceRate: 79,
        nextSession: "2024-02-11",
        status: "Completed",
        progress: "Stable",
        tokensEarned: 350,
    },
    {
        id: 13,
        name: "Isabella Lee",
        condition: "Tennis Elbow",
        adherenceRate: 87,
        nextSession: "2024-02-12",
        status: "Active",
        progress: "Improving",
        tokensEarned: 470,
    },
    {
        id: 14,
        name: "William Brown",
        condition: "Lumbar Strain",
        adherenceRate: 83,
        nextSession: "2024-02-13",
        status: "Active",
        progress: "Stable",
        tokensEarned: 410,
    },
    {
        id: 15,
        name: "Olivia Parker",
        condition: "Frozen Shoulder",
        adherenceRate: 76,
        nextSession: "2024-02-14",
        status: "Active",
        progress: "Declining",
        tokensEarned: 300,
    },
    {
        id: 16,
        name: "Daniel Wong",
        condition: "Plantar Fasciitis",
        adherenceRate: 89,
        nextSession: "2024-02-15",
        status: "Active",
        progress: "Improving",
        tokensEarned: 510,
    },
    {
        id: 17,
        name: "Sophie Martin",
        condition: "Sciatica",
        adherenceRate: 93,
        nextSession: "2024-02-16",
        status: "Active",
        progress: "Stable",
        tokensEarned: 570,
    },
    {
        id: 18,
        name: "Lucas Nguyen",
        condition: "Knee Osteoarthritis",
        adherenceRate: 81,
        nextSession: "2024-02-17",
        status: "Inactive",
        progress: "Stable",
        tokensEarned: 360,
    },
    {
        id: 19,
        name: "Ava Williams",
        condition: "Cervical Spondylosis",
        adherenceRate: 88,
        nextSession: "2024-02-18",
        status: "Active",
        progress: "Improving",
        tokensEarned: 480,
    },
    {
        id: 20,
        name: "Ethan Miller",
        condition: "Meniscus Tear",
        adherenceRate: 85,
        nextSession: "2024-02-19",
        status: "Active",
        progress: "Stable",
        tokensEarned: 430,
    },
    {
        id: 21,
        name: "Charlotte Singh",
        condition: "Thoracic Outlet Syndrome",
        adherenceRate: 84,
        nextSession: "2024-02-20",
        status: "Active",
        progress: "Improving",
        tokensEarned: 420,
    },
    {
        id: 22,
        name: "Alexander Patel",
        condition: "Achilles Tendinitis",
        adherenceRate: 77,
        nextSession: "2024-02-21",
        status: "Active",
        progress: "Declining",
        tokensEarned: 310,
    },
    {
        id: 23,
        name: "Rachel Foster",
        condition: "Fibromyalgia",
        adherenceRate: 82,
        nextSession: "2024-02-22",
        status: "Active",
        progress: "Stable",
        tokensEarned: 390,
    },
    {
        id: 24,
        name: "Kevin Zhang",
        condition: "Bicep Tendonitis",
        adherenceRate: 88,
        nextSession: "2024-02-23",
        status: "Active",
        progress: "Improving",
        tokensEarned: 460,
    },
    {
        id: 25,
        name: "Samantha Cole",
        condition: "Herniated Disc",
        adherenceRate: 79,
        nextSession: "2024-02-24",
        status: "Active",
        progress: "Stable",
        tokensEarned: 340,
    },
    {
        id: 26,
        name: "Benjamin Park",
        condition: "Golfer's Elbow",
        adherenceRate: 91,
        nextSession: "2024-02-25",
        status: "Active",
        progress: "Improving",
        tokensEarned: 530,
    },
    {
        id: 27,
        name: "Victoria Adams",
        condition: "Piriformis Syndrome",
        adherenceRate: 86,
        nextSession: "2024-02-26",
        status: "Active",
        progress: "Stable",
        tokensEarned: 440,
    },
    {
        id: 28,
        name: "Nathan Cooper",
        condition: "Shin Splints",
        adherenceRate: 83,
        nextSession: "2024-02-27",
        status: "Inactive",
        progress: "Declining",
        tokensEarned: 370,
    },
    {
        id: 29,
        name: "Hannah Murphy",
        condition: "Bursitis",
        adherenceRate: 89,
        nextSession: "2024-02-28",
        status: "Active",
        progress: "Improving",
        tokensEarned: 490,
    },
    {
        id: 30,
        name: "Christopher Lee",
        condition: "Whiplash",
        adherenceRate: 77,
        nextSession: "2024-02-29",
        status: "Active",
        progress: "Stable",
        tokensEarned: 320,
    },
    {
        id: 31,
        name: "Grace Wilson",
        condition: "IT Band Syndrome",
        adherenceRate: 92,
        nextSession: "2024-03-01",
        status: "Active",
        progress: "Improving",
        tokensEarned: 560,
    },
    {
        id: 32,
        name: "Andrew Chang",
        condition: "Spinal Stenosis",
        adherenceRate: 84,
        nextSession: "2024-03-02",
        status: "Active",
        progress: "Stable",
        tokensEarned: 420,
    },
    {
        id: 33,
        name: "Julia Santos",
        condition: "Arthritis",
        adherenceRate: 80,
        nextSession: "2024-03-03",
        status: "Active",
        progress: "Declining",
        tokensEarned: 350,
    },
    {
        id: 34,
        name: "Ryan O'Connor",
        condition: "Muscle Strain",
        adherenceRate: 87,
        nextSession: "2024-03-04",
        status: "Active",
        progress: "Improving",
        tokensEarned: 470,
    },
    {
        id: 35,
        name: "Mia Johnson",
        condition: "Scoliosis",
        adherenceRate: 93,
        nextSession: "2024-03-05",
        status: "Active",
        progress: "Stable",
        tokensEarned: 580,
    },
    {
        id: 36,
        name: "Tyler Robinson",
        condition: "Patellar Tendonitis",
        adherenceRate: 81,
        nextSession: "2024-03-06",
        status: "Completed",
        progress: "Improving",
        tokensEarned: 380,
    },
    {
        id: 37,
        name: "Natalie Kim",
        condition: "Cubital Tunnel Syndrome",
        adherenceRate: 88,
        nextSession: "2024-03-07",
        status: "Active",
        progress: "Stable",
        tokensEarned: 460,
    },
    {
        id: 38,
        name: "Marcus Bennett",
        condition: "Calf Strain",
        adherenceRate: 85,
        nextSession: "2024-03-08",
        status: "Active",
        progress: "Improving",
        tokensEarned: 430,
    },
    {
        id: 39,
        name: "Lauren Taylor",
        condition: "De Quervain's Tenosynovitis",
        adherenceRate: 90,
        nextSession: "2024-03-09",
        status: "Active",
        progress: "Stable",
        tokensEarned: 510,
    },
    {
        id: 40,
        name: "Jordan Hayes",
        condition: "Hamstring Strain",
        adherenceRate: 82,
        nextSession: "2024-03-10",
        status: "Active",
        progress: "Declining",
        tokensEarned: 400,
    },
    {
        id: 41,
        name: "Sophia Chen",
        condition: "Postural Dysfunction",
        adherenceRate: 86,
        nextSession: "2024-03-11",
        status: "Active",
        progress: "Improving",
        tokensEarned: 450,
    },
    {
        id: 42,
        name: "Isaac Rodriguez",
        condition: "TMJ Disorder",
        adherenceRate: 83,
        nextSession: "2024-03-12",
        status: "Inactive",
        progress: "Stable",
        tokensEarned: 410,
    }
];


// Mock data
export const mockProgressData: ProgressData[] = [
    { name: 'Week 1', accuracy: 85, sessions: 3, pain: 2, adherence: 65 },
    { name: 'Week 2', accuracy: 87, sessions: 2, pain: 3, adherence: 78 },
    { name: 'Week 3', accuracy: 82, sessions: 4, pain: 1, adherence: 85 },
    { name: 'Week 4', accuracy: 89, sessions: 3, pain: 2, adherence: 82 },
    { name: 'Week 5', accuracy: 91, sessions: 2, pain: 1, adherence: 90 }
];

export const blockchainActivityData = [
    { day: 'Mon', transactions: 45, rewards: 1200, contracts: 12 },
    { day: 'Tue', transactions: 52, rewards: 1400, contracts: 15 },
    { day: 'Wed', transactions: 48, rewards: 1100, contracts: 10 },
    { day: 'Thu', transactions: 61, rewards: 1600, contracts: 18 },
    { day: 'Fri', transactions: 55, rewards: 1300, contracts: 14 },
];

export const mockAIInsights: AIInsight[] = [
    {
        title: "Exercise Pattern Detected",
        description: "Patient shows improved form in lateral movements",
        confidence: 92,
        category: "progress",
        timestamp: "2024-01-30T10:00:00Z"
    },
    {
        title: "Risk Alert",
        description: "Potential overexertion in shoulder exercises",
        confidence: 85,
        category: "risk",
        timestamp: "2024-01-30T09:45:00Z"
    },
    {
        title: "Treatment Optimization",
        description: "Suggesting reduced resistance for next session",
        confidence: 88,
        category: "recommendation",
        timestamp: "2024-01-30T09:30:00Z"
    }
];

export const mockVitals: PatientVitals[] = [
    { heartRate: 75, breathing: 16, movement: 85, painLevel: 2, timestamp: "10:00" },
    { heartRate: 78, breathing: 18, movement: 82, painLevel: 3, timestamp: "10:05" },
    { heartRate: 76, breathing: 17, movement: 88, painLevel: 2, timestamp: "10:10" },
];